server.port=8080

## --- MySQL local (désactivé) ---
#spring.datasource.url=jdbc:mysql://localhost:3306/taekwondodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Mongo local ---
spring.data.mongodb.uri=mongodb+srv://alizeegueye_db_user:BE4YZ98YWKa68qGt@ClubTaekwondo.mongodb.net/taekwondo_db?retryWrites=true&w=majority

## --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- Uploads & limites ---
upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- PostgreSQL local ---
spring.datasource.url=jdbc:postgresql://localhost:5432/taekwondodb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Clés (local) ---
stripe.api.key=sk_test_51QY3k3Bruaz5mgsEw3Ec0zkTYPPVHtL86EFLc33ZdT6oeCJAb7Z0biwJiyr5dpbNKqOlCTZBg979dVl2zSk0XOcM00xQON7Dbm
stripe.public.key=pk_test_51QY3k3Bruaz5mgsEvMmjKUl3R9Q98EqJ2twVTYOVi9nPBrcfVexwtOpSkELyoMAzN0jOf2MvNVM9F9X8O3E2O9JE00YryVYFdp
stripe.webhook.secret=whsec_6c2e7fd0c2fbed60f0b52425742b6c4f60bd67d351a21610f64667b17bd4f149
jwt.secret=NmZlMmJhZGY3ZGVmZTgwZGVkZjdhZTEzYmNlZmNmYzBhYjc=

# --- Configuration Email (LOCAL) ---
# ✅ Configuration Gmail avec la BONNE adresse email
spring.mail.username=alizee.gueye@gmail.com
spring.mail.password=pdte yldn zzde fjmn
app.mail.from=alizee.gueye@gmail.com
app.mail.frontend-url=http://localhost:4200

# ======== DEBUG SÉCURITÉ / LOGS UTILES ========
spring.security.debug=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.club.taekwondo=DEBUG
logging.level.org.springframework.mail=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param