-- Schema fondateur, reconstruit a partir de l'etat reel de la base au 2026-08-20.
-- Remplace l'ancien historique V1-V12 (jamais fiable : le schema n'avait jamais ete
-- cree par Flyway depuis zero, seulement via hibernate.ddl-auto=update en local).
-- La base de production IONOS n'ayant quasiment aucune donnee, elle est reinitialisee
-- avec ce schema propre plutot que de patcher l'historique existant.

CREATE TABLE about_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT,
    badge_label VARCHAR(255),
    description_text VARCHAR(255),
    founded_year VARCHAR(255),
    heading_line1 VARCHAR(255),
    heading_line2 VARCHAR(255),
    image_path VARCHAR(255),
    lead_text VARCHAR(255),
    mission_text VARCHAR(255),
    mission_title VARCHAR(255),
    values_title VARCHAR(255),
    vision_text VARCHAR(255),
    vision_title VARCHAR(255)
);

CREATE TABLE about_chips (
    about_config_id BIGINT NOT NULL,
    chip VARCHAR(255),
    chip_order INTEGER NOT NULL,
    PRIMARY KEY (about_config_id, chip_order)
);

CREATE TABLE about_values (
    about_config_id BIGINT NOT NULL,
    bold VARCHAR(255),
    description VARCHAR(255),
    value_order INTEGER NOT NULL,
    PRIMARY KEY (about_config_id, value_order)
);

CREATE TABLE clubs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    adresse VARCHAR(255),
    email VARCHAR(255),
    logo VARCHAR(255),
    telephone VARCHAR(255),
    rib VARCHAR(255)
);

CREATE TABLE actualites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    titre VARCHAR(255) NOT NULL,
    contenu TEXT NOT NULL,
    date_publication TIMESTAMP NOT NULL,
    type_actu VARCHAR(100),
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    image_url VARCHAR(512),
    complement TEXT,
    extrait VARCHAR(220)
);

CREATE TABLE avis (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT,
    utilisateur_id BIGINT,
    approuve BOOLEAN NOT NULL DEFAULT FALSE,
    contenu TEXT NOT NULL,
    date_pub DATE NOT NULL,
    note SMALLINT,
    photo VARCHAR(10000),
    pseudo_visiteur VARCHAR(100),
    type_avis VARCHAR(50)
);

CREATE TABLE utilisateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT,
    adresse VARCHAR(255),
    date_naissance DATE,
    email VARCHAR(255) NOT NULL UNIQUE,
    nom VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    telephone VARCHAR(255),
    password_temporaire BOOLEAN NOT NULL DEFAULT FALSE,
    password_updated_at TIMESTAMP WITH TIME ZONE,
    genre VARCHAR(20),
    CONSTRAINT utilisateur_role_check CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'PARENT', 'MEMBRE')),
    CONSTRAINT utilisateur_genre_check CHECK (genre IN ('MASCULIN', 'FEMININ', 'NON_PRECISE'))
);

CREATE TABLE membre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT,
    parent_id BIGINT,
    compte_utilisateur_id BIGINT UNIQUE,
    ceinture VARCHAR(255),
    date_naissance DATE,
    est_adulte BOOLEAN NOT NULL,
    nom VARCHAR(255) NOT NULL,
    numero_licence VARCHAR(255) UNIQUE,
    prenom VARCHAR(255) NOT NULL,
    genre VARCHAR(20),
    CONSTRAINT membre_genre_check CHECK (genre IN ('MASCULIN', 'FEMININ', 'NON_PRECISE'))
);

CREATE TABLE commande (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT,
    utilisateur_id BIGINT,
    date_commande DATE NOT NULL,
    date_paiement DATE,
    mode_paiement VARCHAR(255),
    montant_total NUMERIC(10,2),
    statut VARCHAR(50) NOT NULL
);

CREATE TABLE document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membre_id BIGINT,
    utilisateur_id BIGINT NOT NULL,
    chemin_fichier VARCHAR(255) NOT NULL,
    date_depot TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT,
    nom_document VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    type_document VARCHAR(50) NOT NULL,
    motif_refus TEXT
);

CREATE TABLE echeance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paiement_id BIGINT NOT NULL,
    date_echeance DATE NOT NULL,
    date_paiement_reel DATE,
    mode_paiement VARCHAR(255),
    montant DOUBLE PRECISION NOT NULL,
    numero INTEGER,
    reference VARCHAR(255),
    statut VARCHAR(255) NOT NULL
);

CREATE TABLE enseignants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    description VARCHAR(2000),
    facebook VARCHAR(255),
    instagram VARCHAR(255),
    linkedin VARCHAR(255),
    nom VARCHAR(255) NOT NULL,
    photo_url VARCHAR(255),
    prenom VARCHAR(255) NOT NULL,
    specialite VARCHAR(255)
);

CREATE TABLE evenement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    actif BOOLEAN NOT NULL,
    capacite INTEGER NOT NULL,
    date_debut TIMESTAMP(6) NOT NULL,
    date_fin TIMESTAMP(6) NOT NULL,
    description VARCHAR(255),
    image_filename VARCHAR(255),
    lieu VARCHAR(255) NOT NULL,
    titre VARCHAR(255) NOT NULL
);

CREATE TABLE galeries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    titre VARCHAR(255) NOT NULL,
    image_url VARCHAR(512),
    description TEXT,
    date_publication TIMESTAMP NOT NULL
);

CREATE TABLE hero_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eyebrow_text VARCHAR(255),
    identity_mid VARCHAR(255),
    identity_strong VARCHAR(255),
    video_path VARCHAR(255)
);

CREATE TABLE hero_slogans (
    hero_config_id BIGINT NOT NULL,
    slogan VARCHAR(255),
    slogan_order INTEGER NOT NULL,
    PRIMARY KEY (hero_config_id, slogan_order)
);

CREATE TABLE hero_stats (
    hero_config_id BIGINT NOT NULL,
    icon VARCHAR(255),
    label VARCHAR(255),
    value VARCHAR(255),
    stat_order INTEGER NOT NULL,
    PRIMARY KEY (hero_config_id, stat_order)
);

CREATE TABLE horaire (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT,
    adresse VARCHAR(255),
    code_postal VARCHAR(255),
    groupe VARCHAR(255),
    heure_debut VARCHAR(255),
    heure_fin VARCHAR(255),
    jour VARCHAR(255),
    ville VARCHAR(255)
);

CREATE TABLE inscription_evenement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evenement_id BIGINT NOT NULL,
    membre_id BIGINT NOT NULL,
    commentaire VARCHAR(255),
    date_inscription TIMESTAMP(6) NOT NULL,
    presence BOOLEAN,
    statut VARCHAR(255) NOT NULL,
    CONSTRAINT inscription_evenement_statut_check CHECK (statut IN ('EN_ATTENTE', 'VALIDEE', 'ANNULEE')),
    CONSTRAINT uk_inscription_membre_evenement UNIQUE (membre_id, evenement_id)
);

CREATE TABLE produit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT,
    categorie VARCHAR(100),
    description TEXT,
    image_url VARCHAR(255),
    nom VARCHAR(255) NOT NULL,
    prix NUMERIC(10,2) NOT NULL,
    stock INTEGER NOT NULL
);

CREATE TABLE ligne_commande (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id BIGINT NOT NULL,
    produit_id BIGINT NOT NULL,
    beneficiaire_id BIGINT,
    couleur VARCHAR(255),
    flocage VARCHAR(255),
    prix_unitaire DOUBLE PRECISION NOT NULL,
    quantite INTEGER NOT NULL,
    sous_total DOUBLE PRECISION NOT NULL,
    taille VARCHAR(255)
);

CREATE TABLE mentions_legales_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL UNIQUE,
    nom_association VARCHAR(255),
    statut_juridique VARCHAR(255),
    adresse VARCHAR(255),
    numero_rna VARCHAR(100),
    numero_siren VARCHAR(100),
    representant_legal VARCHAR(255),
    email VARCHAR(255),
    telephone VARCHAR(50),
    hebergeur_nom VARCHAR(255),
    hebergeur_adresse VARCHAR(255),
    hebergeur_site_web VARCHAR(255),
    mediateur_nom VARCHAR(255),
    mediateur_contact VARCHAR(255)
);

CREATE TABLE politique_confidentialite_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL UNIQUE,
    nom_association VARCHAR(255),
    adresse VARCHAR(255),
    email_contact VARCHAR(255),
    email_rgpd VARCHAR(255),
    representant_legal VARCHAR(255)
);

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT,
    date_envoi TIMESTAMP(6),
    lu BOOLEAN NOT NULL,
    message VARCHAR(255),
    titre VARCHAR(255),
    type VARCHAR(255),
    lien_action VARCHAR(255)
);

CREATE TABLE paiement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT,
    commande_id BIGINT,
    membre_id BIGINT NOT NULL,
    utilisateur_id BIGINT NOT NULL,
    admin_responsable VARCHAR(255),
    charge_id VARCHAR(100),
    date_annulation TIMESTAMP(6),
    date_paiement DATE,
    echeances_restantes INTEGER,
    echeances_totales INTEGER,
    mode_paiement VARCHAR(255),
    montant_paye DOUBLE PRECISION,
    montant_restant DOUBLE PRECISION,
    montant_total DOUBLE PRECISION,
    motif_annulation VARCHAR(255),
    payment_intent_id VARCHAR(100) UNIQUE,
    receipt_url TEXT,
    statut VARCHAR(255),
    stripe_status VARCHAR(50),
    type VARCHAR(255) NOT NULL
);

CREATE TABLE parametres_paiement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    echeances_autorisees INTEGER NOT NULL,
    especes BOOLEAN NOT NULL,
    intervalle_echeance VARCHAR(255) NOT NULL,
    mode_paiement_par_defaut VARCHAR(255) NOT NULL,
    montant_cotisation DOUBLE PRECISION NOT NULL,
    stripe BOOLEAN NOT NULL,
    virement BOOLEAN NOT NULL
);

CREATE TABLE reinitialisation_mot_de_passe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT,
    date_expiration TIMESTAMP(6),
    token VARCHAR(255),
    utilise BOOLEAN NOT NULL
);

CREATE TABLE required_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    code VARCHAR(100) NOT NULL,
    label VARCHAR(255) NOT NULL,
    order_index INTEGER,
    required BOOLEAN NOT NULL,
    CONSTRAINT uk_required_document_club_code UNIQUE (club_id, code)
);

CREATE TABLE revoked_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_key VARCHAR(512) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Index

CREATE INDEX idx_actualites_club_id ON actualites (club_id);
CREATE INDEX idx_actualites_featured ON actualites (is_featured);
CREATE INDEX idx_echeance_paiement ON echeance (paiement_id);
CREATE INDEX idx_galeries_club_id ON galeries (club_id);
CREATE INDEX idx_paiement_intent ON paiement (payment_intent_id);
CREATE INDEX idx_paiement_membre ON paiement (membre_id);
CREATE INDEX idx_paiement_utilisateur ON paiement (utilisateur_id);
CREATE INDEX idx_revoked_token_expiry ON revoked_tokens (expires_at);
CREATE INDEX idx_revoked_token_key ON revoked_tokens (token_key);

-- Cles etrangeres (ajoutees apres toutes les tables pour eviter les problemes d'ordre)

ALTER TABLE about_config ADD CONSTRAINT fk_about_config_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE about_config ADD CONSTRAINT uq_about_config_club UNIQUE (club_id);
ALTER TABLE about_chips ADD CONSTRAINT fk_about_chips_config FOREIGN KEY (about_config_id) REFERENCES about_config(id);
ALTER TABLE about_values ADD CONSTRAINT fk_about_values_config FOREIGN KEY (about_config_id) REFERENCES about_config(id);

ALTER TABLE actualites ADD CONSTRAINT fk_actualites_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE avis ADD CONSTRAINT fk_avis_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE avis ADD CONSTRAINT fk_avis_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id);

ALTER TABLE utilisateur ADD CONSTRAINT fk_utilisateur_club FOREIGN KEY (club_id) REFERENCES clubs(id);

ALTER TABLE membre ADD CONSTRAINT fk_membre_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE membre ADD CONSTRAINT fk_membre_parent FOREIGN KEY (parent_id) REFERENCES utilisateur(id);
ALTER TABLE membre ADD CONSTRAINT fk_membre_compte_utilisateur FOREIGN KEY (compte_utilisateur_id) REFERENCES utilisateur(id);

ALTER TABLE commande ADD CONSTRAINT fk_commande_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE commande ADD CONSTRAINT fk_commande_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id);

ALTER TABLE document ADD CONSTRAINT fk_document_membre FOREIGN KEY (membre_id) REFERENCES membre(id);
ALTER TABLE document ADD CONSTRAINT fk_document_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id);

ALTER TABLE echeance ADD CONSTRAINT fk_echeance_paiement FOREIGN KEY (paiement_id) REFERENCES paiement(id);

ALTER TABLE enseignants ADD CONSTRAINT fk_enseignants_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE evenement ADD CONSTRAINT fk_evenement_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE galeries ADD CONSTRAINT fk_galeries_club FOREIGN KEY (club_id) REFERENCES clubs(id);

ALTER TABLE hero_slogans ADD CONSTRAINT fk_hero_slogans_config FOREIGN KEY (hero_config_id) REFERENCES hero_config(id);
ALTER TABLE hero_stats ADD CONSTRAINT fk_hero_stats_config FOREIGN KEY (hero_config_id) REFERENCES hero_config(id);

ALTER TABLE horaire ADD CONSTRAINT fk_horaire_club FOREIGN KEY (club_id) REFERENCES clubs(id);

ALTER TABLE inscription_evenement ADD CONSTRAINT fk_inscription_evenement FOREIGN KEY (evenement_id) REFERENCES evenement(id);
ALTER TABLE inscription_evenement ADD CONSTRAINT fk_inscription_membre FOREIGN KEY (membre_id) REFERENCES membre(id);

ALTER TABLE produit ADD CONSTRAINT fk_produit_club FOREIGN KEY (club_id) REFERENCES clubs(id);

ALTER TABLE ligne_commande ADD CONSTRAINT fk_ligne_commande_commande FOREIGN KEY (commande_id) REFERENCES commande(id);
ALTER TABLE ligne_commande ADD CONSTRAINT fk_ligne_commande_produit FOREIGN KEY (produit_id) REFERENCES produit(id);
ALTER TABLE ligne_commande ADD CONSTRAINT fk_ligne_commande_beneficiaire FOREIGN KEY (beneficiaire_id) REFERENCES membre(id);

ALTER TABLE mentions_legales_config ADD CONSTRAINT fk_mentions_legales_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE politique_confidentialite_config ADD CONSTRAINT fk_politique_confidentialite_club FOREIGN KEY (club_id) REFERENCES clubs(id);

ALTER TABLE notification ADD CONSTRAINT fk_notification_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id);

ALTER TABLE paiement ADD CONSTRAINT fk_paiement_club FOREIGN KEY (club_id) REFERENCES clubs(id);
ALTER TABLE paiement ADD CONSTRAINT fk_paiement_commande FOREIGN KEY (commande_id) REFERENCES commande(id);
ALTER TABLE paiement ADD CONSTRAINT fk_paiement_membre FOREIGN KEY (membre_id) REFERENCES membre(id);
ALTER TABLE paiement ADD CONSTRAINT fk_paiement_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id);

ALTER TABLE parametres_paiement ADD CONSTRAINT fk_parametres_paiement_club FOREIGN KEY (club_id) REFERENCES clubs(id);

ALTER TABLE reinitialisation_mot_de_passe ADD CONSTRAINT fk_reinitialisation_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id);

ALTER TABLE required_document ADD CONSTRAINT fk_required_document_club FOREIGN KEY (club_id) REFERENCES clubs(id);
